import {
  Organization,
  User,
  Department,
  Designation,
  Employee,
  AttendanceRecord,
  ShiftSchedule,
  LeaveBalance,
  LeaveRequest,
  Holiday,
  PayrollRecord,
  NotificationItem,
  TaskItem,
  Announcement,
  ExpenseClaim,
  DocumentItem,
  AssetItem,
} from '../types';

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-1',
    name: 'Acme Corp',
    slug: 'acme-corp',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    plan: 'Business',
    status: 'active',
    industry: 'Technology & Software',
    totalEmployees: 248,
    maxEmployees: 500,
    contactEmail: 'admin@acmecorp.com',
    contactPhone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    website: 'https://acmecorp.example.com',
    createdAt: '2024-01-15',
    billingCycle: 'monthly',
    monthlyFee: 1499,
  },
  {
    id: 'org-2',
    name: 'Global Tech Solutions',
    slug: 'global-tech',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&auto=format&fit=crop&q=80',
    plan: 'Pro',
    status: 'active',
    industry: 'Financial Services',
    totalEmployees: 48,
    maxEmployees: 100,
    contactEmail: 'contact@globaltech.io',
    contactPhone: '+1 (555) 987-6543',
    location: 'New York, NY',
    website: 'https://globaltech.example.com',
    createdAt: '2024-02-10',
    billingCycle: 'annual',
    monthlyFee: 699,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-hr-admin',
    name: 'Sneha Gupta',
    email: 'hr.admin@acmecorp.com',
    role: 'hr_admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Human Resources',
    designation: 'HR Director',
    status: 'active',
    createdAt: '2024-01-20',
  },
  {
    id: 'user-manager',
    name: 'Michael Chen',
    email: 'engineering.lead@acmecorp.com',
    role: 'manager',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Engineering',
    designation: 'VP of Engineering',
    status: 'active',
    createdAt: '2024-01-22',
  },
  {
    id: 'user-employee',
    name: 'Sarah Wilson',
    email: 'employee@acmecorp.com',
    role: 'employee',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Design & Engineering',
    designation: 'Senior Product Designer',
    employeeId: 'EMP-0412',
    status: 'active',
    createdAt: '2024-02-15',
  },
  {
    id: 'user-payroll-admin',
    name: 'Aisha Patel',
    email: 'payroll.specialist@acmecorp.com',
    role: 'payroll_admin',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Finance',
    designation: 'Payroll Manager',
    status: 'active',
    createdAt: '2024-02-05',
  },
  {
    id: 'user-saas-owner',
    name: 'Alexander Wright',
    email: 'saas.owner@hrmplatform.com',
    role: 'saas_owner',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    organizationId: 'platform',
    organizationName: 'HRM Platform HQ',
    designation: 'SaaS Platform Owner',
    status: 'active',
    createdAt: '2023-01-01',
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'dept-1', organizationId: 'org-1', name: 'Engineering', code: 'ENG', employeeCount: 28, color: '#3B82F6' },
  { id: 'dept-2', organizationId: 'org-1', name: 'Human Resources', code: 'HR', employeeCount: 12, color: '#F59E0B' },
  { id: 'dept-3', organizationId: 'org-1', name: 'Marketing', code: 'MKT', employeeCount: 16, color: '#06B6D4' },
  { id: 'dept-4', organizationId: 'org-1', name: 'Sales', code: 'SLS', employeeCount: 14, color: '#EF4444' },
  { id: 'dept-5', organizationId: 'org-1', name: 'Finance', code: 'FIN', employeeCount: 10, color: '#8B5CF6' },
  { id: 'dept-6', organizationId: 'org-1', name: 'Operations', code: 'OPS', employeeCount: 8, color: '#38BDF8' },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    organizationId: 'org-1',
    employeeId: 'EMP-0412',
    firstName: 'Sarah',
    lastName: 'Wilson',
    fullName: 'Sarah Wilson',
    email: 'sarah.wilson@acmecorp.com',
    personalEmail: 'sarah.wilson.design@gmail.com',
    phone: '+1 (555) 432-8910',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    department: 'Design & Engineering',
    designation: 'Senior Product Designer',
    joiningDate: '2022-03-15',
    employmentType: 'Full-time',
    workLocation: 'Hybrid',
    officeLocation: 'San Francisco, HQ Floor 3',
    status: 'Active',
    salary: {
      basic: 4500,
      hra: 1200,
      allowances: 800,
      gross: 6500,
      deductions: {
        providentFund: 450,
        professionalTax: 50,
        incomeTax: 600,
        insurance: 150,
      },
      net: 5250,
    },
  },
  {
    id: 'emp-2',
    organizationId: 'org-1',
    employeeId: 'EMP-0105',
    firstName: 'Rohit',
    lastName: 'Sharma',
    fullName: 'Rohit Sharma',
    email: 'rohit.sharma@acmecorp.com',
    phone: '+91 98765 43210',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=95',
    department: 'Human Resources',
    designation: 'HR Executive',
    joiningDate: '2022-01-15',
    employmentType: 'Full-time',
    workLocation: 'On-site',
    officeLocation: 'Noida Tech Park, Tower B',
    status: 'Active',
  },
  {
    id: 'emp-3',
    organizationId: 'org-1',
    employeeId: 'EMP-0204',
    firstName: 'Michael',
    lastName: 'Chen',
    fullName: 'Michael Chen',
    email: 'michael.chen@acmecorp.com',
    phone: '+1 (555) 345-6789',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    designation: 'VP of Engineering',
    joiningDate: '2021-08-01',
    employmentType: 'Full-time',
    workLocation: 'Hybrid',
    status: 'Active',
  },
  {
    id: 'emp-4',
    organizationId: 'org-1',
    employeeId: 'EMP-0318',
    firstName: 'Emily',
    lastName: 'Davis',
    fullName: 'Emily Davis',
    email: 'emily.davis@acmecorp.com',
    phone: '+1 (555) 789-1234',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    designation: 'Marketing Lead',
    joiningDate: '2023-04-10',
    employmentType: 'Full-time',
    workLocation: 'Remote',
    status: 'Active',
  },
];

export const INITIAL_LEAVE_RECORDS: LeaveRequest[] = [
  {
    id: 'leave-1',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeCode: 'EMP-0412',
    employeeName: 'Sarah Wilson',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    leaveType: 'Casual Leave',
    startDate: 'Apr 12, 2025',
    endDate: 'Apr 12, 2025',
    days: 1,
    reason: 'Personal family matter',
    status: 'Approved',
    appliedDate: '2025-04-05',
    approverName: 'Michael Chen',
  },
  {
    id: 'leave-2',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeCode: 'EMP-0412',
    employeeName: 'Sarah Wilson',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    leaveType: 'Sick Leave',
    startDate: 'Apr 08, 2025',
    endDate: 'Apr 09, 2025',
    days: 2,
    reason: 'Fever and viral illness',
    status: 'Approved',
    appliedDate: '2025-04-07',
    approverName: 'Michael Chen',
  },
  {
    id: 'leave-3',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeCode: 'EMP-0412',
    employeeName: 'Sarah Wilson',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    leaveType: 'Casual Leave',
    startDate: 'Mar 28, 2025',
    endDate: 'Mar 29, 2025',
    days: 2,
    reason: 'Out of station trip',
    status: 'Approved',
    appliedDate: '2025-03-20',
  },
  {
    id: 'leave-4',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeCode: 'EMP-0412',
    employeeName: 'Sarah Wilson',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    leaveType: 'Earned Leave',
    startDate: 'Mar 15, 2025',
    endDate: 'Mar 17, 2025',
    days: 3,
    reason: 'Annual vacation break',
    status: 'Approved',
    appliedDate: '2025-03-01',
  },
  {
    id: 'leave-5',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeCode: 'EMP-0412',
    employeeName: 'Sarah Wilson',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    leaveType: 'Casual Leave',
    startDate: 'May 27, 2025',
    endDate: 'May 28, 2025',
    days: 2,
    reason: 'Family wedding event',
    status: 'Pending',
    appliedDate: '2025-05-10',
  },
  {
    id: 'leave-6',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeCode: 'EMP-0412',
    employeeName: 'Sarah Wilson',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    leaveType: 'Casual Leave',
    startDate: 'Jan 22, 2025',
    endDate: 'Jan 24, 2025',
    days: 3,
    reason: 'Urgent household relocation',
    status: 'Rejected',
    appliedDate: '2025-01-15',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Leave Request Approved',
    message: 'Your Casual Leave application for May 20 was approved by Michael Chen.',
    type: 'success',
    timestamp: '10 mins ago',
    isRead: false,
  },
  {
    id: 'notif-2',
    title: 'Monthly Payslip Available',
    message: 'Payslip for May 2024 has been generated and is ready for download.',
    type: 'info',
    timestamp: '2 hours ago',
    isRead: false,
  },
  {
    id: 'notif-3',
    title: 'Upcoming Team Meeting',
    message: 'Design system sprint planning scheduled for tomorrow at 10:00 AM.',
    type: 'warning',
    timestamp: '1 day ago',
    isRead: true,
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  { id: 1, text: 'Complete performance review self-assessment', dueDate: 'May 22, 2024', priority: 'High', completed: false },
  { id: 2, text: 'Submit April travel expense report', dueDate: 'May 24, 2024', priority: 'Medium', completed: false },
  { id: 3, text: 'Update emergency contact details in HR portal', dueDate: 'May 28, 2024', priority: 'Low', completed: false },
  { id: 4, text: 'Review mobile design sprint deliverables', dueDate: 'May 30, 2024', priority: 'High', completed: true },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'anc-1',
    title: 'Office will be closed on May 25, 2024',
    subtitle: 'Public Holiday notice for all regional offices.',
    content: 'All branches will remain closed for the upcoming Memorial Day public holiday. Emergency IT on-call is available.',
    time: '2 hours ago',
    category: 'Holiday',
    author: 'Sneha Gupta',
  },
  {
    id: 'anc-2',
    title: 'New HR Policy & Hybrid Guidelines Update',
    subtitle: 'Please review the updated policy on flexible work hours.',
    content: 'The executive committee has approved expanded flexible core hours starting from 10:00 AM to 04:00 PM.',
    time: '5 hours ago',
    category: 'Policy',
    author: 'HR Department',
  },
  {
    id: 'anc-3',
    title: 'Annual Team Building & Hackathon Event',
    subtitle: 'Join us for the 2024 summer innovation fest.',
    content: 'Registration for team tracks is now open. Prizes include tech gadgets and additional paid time off.',
    time: '1 day ago',
    category: 'Event',
    author: 'People Ops',
  },
];

export const INITIAL_PAYSLIPS: PayrollRecord[] = [
  {
    id: 'ps-1',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeCode: 'EMP-0412',
    employeeName: 'Sarah Wilson',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    designation: 'Senior Product Designer',
    month: 'May 2024',
    basicSalary: 4500,
    hra: 1200,
    allowances: 800,
    bonus: 0,
    grossSalary: 6500,
    providentFund: 450,
    taxDeduction: 600,
    insuranceDeduction: 150,
    totalDeductions: 1200,
    netSalary: 5300,
    paymentMethod: 'Direct Deposit',
    paymentDate: '2024-05-31',
    status: 'Paid',
  },
  {
    id: 'ps-2',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeCode: 'EMP-0412',
    employeeName: 'Sarah Wilson',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    designation: 'Senior Product Designer',
    month: 'Apr 2024',
    basicSalary: 4500,
    hra: 1200,
    allowances: 800,
    bonus: 0,
    grossSalary: 6500,
    providentFund: 450,
    taxDeduction: 600,
    insuranceDeduction: 150,
    totalDeductions: 1200,
    netSalary: 5300,
    paymentMethod: 'Direct Deposit',
    paymentDate: '2024-04-30',
    status: 'Paid',
  },
  {
    id: 'ps-3',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeCode: 'EMP-0412',
    employeeName: 'Sarah Wilson',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Design',
    designation: 'Senior Product Designer',
    month: 'Mar 2024',
    basicSalary: 4500,
    hra: 1200,
    allowances: 800,
    bonus: 500,
    grossSalary: 7000,
    providentFund: 450,
    taxDeduction: 650,
    insuranceDeduction: 150,
    totalDeductions: 1250,
    netSalary: 5750,
    paymentMethod: 'Direct Deposit',
    paymentDate: '2024-03-31',
    status: 'Paid',
  },
];

export const INITIAL_HOLIDAYS: Holiday[] = [
  { id: 'hol-1', organizationId: 'org-1', name: 'Memorial Day', date: 'May 25, 2024', day: 'Saturday', type: 'Public' },
  { id: 'hol-2', organizationId: 'org-1', name: 'Independence Day', date: 'Jul 04, 2024', day: 'Thursday', type: 'Public' },
  { id: 'hol-3', organizationId: 'org-1', name: 'Labor Day', date: 'Sep 02, 2024', day: 'Monday', type: 'Public' },
  { id: 'hol-4', organizationId: 'org-1', name: 'Thanksgiving Day', date: 'Nov 28, 2024', day: 'Thursday', type: 'Public' },
  { id: 'hol-5', organizationId: 'org-1', name: 'Winter Break', date: 'Dec 25, 2024', day: 'Wednesday', type: 'Company' },
];

export const INITIAL_EXPENSES: ExpenseClaim[] = [
  { id: 'exp-1', title: 'Client Lunch in SF', category: 'Meals & Entertainment', amount: 124.50, date: '2024-05-18', status: 'Approved' },
  { id: 'exp-2', title: 'Software Design License', category: 'Software Subscription', amount: 89.00, date: '2024-05-12', status: 'Approved' },
  { id: 'exp-3', title: 'Ergonomic Mouse & Mat', category: 'Office Hardware', amount: 65.00, date: '2024-05-20', status: 'Pending' },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  { id: 'doc-1', title: 'Employment Contract & NDA', category: 'Legal', size: '2.4 MB', updatedAt: 'Jan 15, 2022' },
  { id: 'doc-2', title: 'Health Insurance Card & Benefits', category: 'Benefits', size: '1.1 MB', updatedAt: 'Jan 10, 2024' },
  { id: 'doc-3', title: 'Employee Handbook 2024', category: 'Company Policies', size: '4.8 MB', updatedAt: 'Jan 01, 2024' },
  { id: 'doc-4', title: 'Annual Tax Declaration Form', category: 'Finance', size: '650 KB', updatedAt: 'Mar 15, 2024' },
];

export const INITIAL_ASSETS: AssetItem[] = [
  { id: 'ast-1', name: 'MacBook Pro 16" M2 Max', category: 'Laptop', serialNumber: 'C02G849XMD6T', assignedDate: 'Jan 15, 2022', status: 'Active' },
  { id: 'ast-2', name: 'Dell UltraSharp 32" 4K Monitor', category: 'Display', serialNumber: 'CN-098K4-716', assignedDate: 'Jan 20, 2022', status: 'Active' },
  { id: 'ast-3', name: 'Apple Magic Keyboard & Mouse', category: 'Peripherals', serialNumber: 'A1644-KB91', assignedDate: 'Jan 15, 2022', status: 'Active' },
];
